[build]
  publish = "build"
  command = "echo 'Using pre-built files'"

[build.environment]
  REACT_APP_BACKEND_URL = "https://cryptogig-production.up.railway.app"
  REACT_APP_WALLETCONNECT_PROJECT_ID = "2f05a7cde2bb14b478f07c00594118b1"
  REACT_APP_USDC_ADDRESS = "0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582"
  REACT_APP_CONTRACT_ADDRESS = ""
  REACT_APP_GOOGLE_CLIENT_ID = ""
  REACT_APP_GITHUB_CLIENT_ID = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://cryptogig-production.up.railway.app"