[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_BACKEND_URL = "https://clientarbitrator-production.up.railway.app"
  VITE_WALLETCONNECT_PROJECT_ID = "2f05a7cde2bb14b478f07c00594118b1"
  VITE_USDC_ADDRESS = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
  VITE_CONTRACT_ADDRESS = "0x8A808f52b19F07C53981b4f43f84E80972F468C7"
  VITE_CHAIN_ID = "11155111"
  VITE_GOOGLE_CLIENT_ID = ""
  VITE_GITHUB_CLIENT_ID = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "https://clientarbitrator-production.up.railway.app"
